[
    {
        "niplama": "340012215",
        "nipbaru": "196612311989031013",
        "namagelar": "Muhlis ,SE, M.Si",
        "urutreog": "4 ",
        "kdorg": "92800",
        "nmorg": "BPS Kabupaten/Kota",
        "nmjab": "Kepala BPS Kabupaten/Kota",
        "flagwil": "5 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "42",
        "nmgol": "IV/b ",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "3"
    },
    {
        "niplama": "340011923",
        "nipbaru": "196410301988031002",
        "namagelar": "Arsyad Kadir",
        "urutreog": "6 ",
        "kdorg": "92810",
        "nmorg": "Subbagian Tata Usaha",
        "nmjab": "Kepala Subbagian Tata Usaha",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "4"
    },
    {
        "niplama": "340016783",
        "nipbaru": "197801102002122005",
        "namagelar": "Suriani ,S.Kel",
        "urutreog": "4 ",
        "kdorg": "92810",
        "nmorg": "Subbagian Tata Usaha",
        "nmjab": "Staf Subbagian Tata Usaha",
        "flagwil": "3 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "33",
        "nmgol": "III/c",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340019877",
        "nipbaru": "196512312007011659",
        "namagelar": "Untung",
        "urutreog": "4 ",
        "kdorg": "92810",
        "nmorg": "Subbagian Tata Usaha",
        "nmjab": "Staf Subbagian Tata Usaha",
        "flagwil": "3 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "21",
        "nmgol": "II/a ",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340056159",
        "nipbaru": "198510302012122002",
        "namagelar": "Irma Suryani ,S.Si",
        "urutreog": "4 ",
        "kdorg": "92810",
        "nmorg": "Subbagian Tata Usaha",
        "nmjab": "Staf Subbagian Tata Usaha",
        "flagwil": "7 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "32",
        "nmgol": "III/b",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340018478",
        "nipbaru": "197410112006041002",
        "namagelar": "Muhamad Kadarsah ,SP",
        "urutreog": "5 ",
        "kdorg": "92820",
        "nmorg": "Seksi Statistik Sosial",
        "nmjab": "Kepala Seksi Statistik Sosial",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "33",
        "nmgol": "III/c",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "4"
    },
    {
        "niplama": "340056198",
        "nipbaru": "199107102013111001",
        "namagelar": "Agung Darwin ,SST",
        "urutreog": "5 ",
        "kdorg": "92820",
        "nmorg": "Seksi Statistik Sosial",
        "nmjab": "Staf Seksi Statistik Sosial",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "32",
        "nmgol": "III/b",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340058314",
        "nipbaru": "199504172018021001",
        "namagelar": "Kurniawan Arief Prasetyo ,SST",
        "urutreog": "6 ",
        "kdorg": "92820",
        "nmorg": "Seksi Statistik Sosial",
        "nmjab": "Staf Seksi Statistik Sosial",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340057917",
        "nipbaru": "199409032017011001",
        "namagelar": "Naufal Fahmi Zakiuddin ,SST",
        "urutreog": "6 ",
        "kdorg": "92830",
        "nmorg": "Seksi Statistik Produksi",
        "nmjab": "Staf Seksi Statistik Produksi",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340011963",
        "nipbaru": "196301011988031004",
        "namagelar": "Amiruddin ,SE",
        "urutreog": "5 ",
        "kdorg": "92840",
        "nmorg": "Seksi Statistik Distribusi",
        "nmjab": "Kepala Seksi Statistik Distribusi",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "4"
    },
    {
        "niplama": "340057922",
        "nipbaru": "199311062017011001",
        "namagelar": "Zulfikar Halim Lumintang ,SST",
        "urutreog": "6 ",
        "kdorg": "92840",
        "nmorg": "Seksi Statistik Distribusi",
        "nmjab": "Staf Seksi Statistik Distribusi",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340012064",
        "nipbaru": "196503161989021001",
        "namagelar": "Muslimin ,SP",
        "urutreog": "5 ",
        "kdorg": "92850",
        "nmorg": "Seksi Neraca Wilayah dan Analisis Statistik",
        "nmjab": "Kepala Seksi Neraca Wilayah dan Analisis Statistik",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "4"
    },
    {
        "niplama": "340058166",
        "nipbaru": "199503302018022001",
        "namagelar": "Atika Putri Purwaningrum ,SST",
        "urutreog": "6 ",
        "kdorg": "92850",
        "nmorg": "Seksi Neraca Wilayah dan Analisis Statistik",
        "nmjab": "Staf Seksi Neraca Wilayah dan Analisis Statistik",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340057317",
        "nipbaru": "199306162016021002",
        "namagelar": "Bakri Malik Ahmad Ismael ,SST",
        "urutreog": "6 ",
        "kdorg": "92850",
        "nmorg": "Seksi Neraca Wilayah dan Analisis Statistik",
        "nmjab": "Staf Seksi Neraca Wilayah dan Analisis Statistik",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340050220",
        "nipbaru": "198610302009021001",
        "namagelar": "Rietmianggara Yudha Candra ,SST",
        "urutreog": "4 ",
        "kdorg": "92860",
        "nmorg": "Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "nmjab": "Kepala Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "flagwil": "7 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "4",
        "nmstjab": "Struktural",
        "kdesl": "4"
    },
    {
        "niplama": "340057659",
        "nipbaru": "199306192016022001",
        "namagelar": "Yunita Nur Khasanah ,SST",
        "urutreog": "5 ",
        "kdorg": "92860",
        "nmorg": "Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "nmjab": "Penugasan Pranata Komputer Pelaksana Lanjutan Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340058367",
        "nipbaru": "199402242018021001",
        "namagelar": "Muh. Shamad ,SST",
        "urutreog": "6 ",
        "kdorg": "92860",
        "nmorg": "Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "nmjab": "Staf Seksi Integrasi Pengolahan dan Diseminasi Statistik",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "000",
        "nmwil": "Kab. Kolaka",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340052272",
        "nipbaru": "197409132009011005",
        "namagelar": "Sapari",
        "urutreog": "5 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "010",
        "nmwil": "Kec. Watubangga",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340018391",
        "nipbaru": "197907182006041005",
        "namagelar": "Alim Bakhri",
        "urutreog": "5 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "KSK",
        "flagwil": "9 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "011",
        "nmwil": "Kec. Tanggetada",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "3",
        "nmstjab": "Fungsional Umum",
        "kdesl": ""
    },
    {
        "niplama": "340055488",
        "nipbaru": "197606092011011006",
        "namagelar": "Amrullah ,SE",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "KSK",
        "flagwil": "6 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "013",
        "nmwil": "Kec. Polinggona",
        "kdgol": "32",
        "nmgol": "III/b",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340019082",
        "nipbaru": "197010042006041011",
        "namagelar": "Asri Samsu Alam",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "6 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "020",
        "nmwil": "Kec. Pomalaa",
        "kdgol": "31",
        "nmgol": "III/a",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052038",
        "nipbaru": "197509262009011003",
        "namagelar": "Ashadi",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "6 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "030",
        "nmwil": "Kec. Wundulako",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052104",
        "nipbaru": "197510102009012006",
        "namagelar": "Hasnawati P.",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "031",
        "nmwil": "Kec. Baula",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340011801",
        "nipbaru": "196412311988021002",
        "namagelar": "Jufiadi",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Penyelia KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "040",
        "nmwil": "Kec. Ladongi",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052017",
        "nipbaru": "197204032009011009",
        "namagelar": "Agus",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "041",
        "nmwil": "Kec. Lambadia",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052285",
        "nipbaru": "197301012009012001",
        "namagelar": "Sunarti",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "042",
        "nmwil": "Kec. Poli-polia",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340013115",
        "nipbaru": "196909071992031002",
        "namagelar": "Herianto",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Penyelia KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "050",
        "nmwil": "Kec. Tirawuta",
        "kdgol": "34",
        "nmgol": "III/d",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052190",
        "nipbaru": "197306122009012003",
        "namagelar": "Marniati",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "6 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "060",
        "nmwil": "Kec. Kolaka",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340052128",
        "nipbaru": "198204062009011008",
        "namagelar": "Idhar Rahim",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "070",
        "nmwil": "Kec. Wolo",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    },
    {
        "niplama": "340053152",
        "nipbaru": "197803262009111001",
        "namagelar": "Sanur Saprah",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "KSK",
        "flagwil": "4 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "071",
        "nmwil": "Kec. Samaturu",
        "kdgol": "23",
        "nmgol": "II/c ",
        "kdstjab": "1",
        "nmstjab": "Staf",
        "kdesl": ""
    },
    {
        "niplama": "340052049",
        "nipbaru": "197304012009011007",
        "namagelar": "Bobi Sahrun",
        "urutreog": "4 ",
        "kdorg": "92870",
        "nmorg": "KSK",
        "nmjab": "Statistisi Pelaksana Lanjutan KSK",
        "flagwil": "6 ",
        "kdprop": "74",
        "kdkab": "04",
        "kdkec": "080",
        "nmwil": "Kec. Mowewe",
        "kdgol": "24",
        "nmgol": "II/d ",
        "kdstjab": "2",
        "nmstjab": "Fungsional Tertentu",
        "kdesl": ""
    }
]
